spring:
  application:
    name: Payment-Routing-Engine
  datasource:
    url: jdbc:postgresql://localhost:5432/payment_routing
    username: postgres
    password: postgres
  docker:
    compose:
      lifecycle-management: start-and-stop
      stop:
        command: down
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
